---
- import_role:
    name: node-webpage
    vars_from: "net-worth"

- name: Setup cron job import
  cron:
    name: "net-worth import"
    minute: "05"
    hour: "*/12"
    user: root
    job: "curl -X POST localhost:{{ net_worth_service_port }}/import"

- name: Setup cron job fill daily
  cron:
    name: "net-worth fill"
    minute: "10"
    hour: "0"
    user: root
    job: "curl -X PUT localhost:{{ net_worth_service_port }}/fill-daily"
