---
- name: Creates directory
  file:
    path: "{{ net_worth_path }}/api"
    state: directory

- name: Creates log directory
  file:
    path: "/var/log/net-worth"
    state: directory

- name: Systemd service
  template:
    src: net-worth.service.j2
    dest: /etc/systemd/system/net-worth.service
    owner: root
    group: root
    mode: 0644
  notify: restart net-worth

- name: Temp .js file
  template:
    src: helloworld.js.j2
    dest: "{{ net_worth_path }}/api/helloworld.js"
    owner: root
    group: root
    mode: 0644

- name: Temp package.json file
  template:
    src: package.json
    dest: "{{ net_worth_path }}/api/package.json"
    owner: root
    group: root
    mode: 0644

- name: Start service
  systemd:
    name: net-worth
    state: started
    enabled: true

- name: Setup cron job import
  cron:
    name: net-worth import
    minute: "05"
    user: root
    job: "curl -X POST localhost:{{ net_worth_service_port }}/import"

- name: Setup cron job fill daily
  cron:
    name: net-worth fill
    minute: "10"
    hour: "0"
    user: root
    job: "curl -X PUT localhost:{{ net_worth_service_port }}/fill-daily"

- name: Setup cron job for backup
  cron:
    name: net-worth backup
    minute: "33"
    user: root
    job: "{{ backup_script_path }}"

- name: Backup to dropbox script
  template:
    src: backup.sh.j2
    dest: "{{ backup_script_path }}"
    owner: root
    group: root
    mode: 0755
