---
- hosts: all
  remote_user: root
  gather_facts: false
  vars_files: "./variables/settings.yml"
  roles:
    - role: setup
      vars:
        create_user: kraag22
      tags: setup

- hosts: ocean
  gather_facts: true
  vars_files: "./variables/settings.yml"
  become: true
  roles:
    - role: antoiner77.caddy
      vars:
        caddy_home: /srv/caddy
        caddy_log_dir: /var/log/caddy
        caddy_log_file: "{{ caddy_log_dir }}/caddy.log"
        caddy_systemd_restart: "on-success"
        caddy_systemd_capabilities_enabled: true
        tls_email: "{{ email_address }}"
        caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
      tags: caddy

    - role: geerlingguy.nodejs
      tags: node

    - role: graphs
      tags: graphs

    - role: blog
      tags: blog

    - role: berlingame
      tags: berlingame

    - role: net-worth
      tags: net-worth
