---
node_webpage_path: /srv/net_worth
node_webpage_log_path: /var/log/net_worth
node_webpage_backup_script_path: /srv/backup-net-worth.sh
node_webpage_user: "net-worth"
node_webpage_group: "net-worth"
node_webpage_service_name: net-worth
node_webpage_service_port: "{{ net_worth_service_port }}"
