---
- name: Creates directory
  file:
    path: "{{ berlingame_path }}"
    state: directory

- name: Creates compose directory
  file:
    path: "{{ compose_path }}"
    state: directory

- git:
    repo: "{{ github_repo }}"
    dest: "{{ berlingame_path }}"
    force: true

- name: Allow write to logs
  file:
    dest: "{{ berlingame_path }}/log"
    owner: root
    group: root
    mode: 0777
    recurse: yes

- name: Allow write to include
  file:
    dest: "{{ berlingame_path }}/include"
    owner: root
    group: root
    mode: 0777
    recurse: yes

- name: Update berlingame php config
  template:
    src: config.php.j2
    dest: "{{ berlingame_path }}/config/config.php"
    owner: root
    group: root
    mode: 0644

- name: Decker compose file
  template:
    src: compose.j2
    dest: "{{ compose_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0644

- name: Systemd service
  template:
    src: berlingame.service.j2
    dest: /etc/systemd/system/berlingame.service
    owner: root
    group: root
    mode: 0644
  notify: restart berlingame

- name: Start service
  systemd:
    name: berlingame
    state: started
    enabled: true

- name: Set timezone for cron
  ansible.builtin.cron:
    name: CRON_TZ
    env: yes
    job: "{{ cron_timezone }}"

- name: Run job every midnight
  ansible.builtin.cron:
    name: berlingame midnight
    minute: "0"
    hour: "23"
    user: root
    job: "wget localhost:{{ berlingame_service_port }}/prepocet.php?heslo={{ prepocet_password }} > /dev/null"


- name: Run SQL import
  import_role:
    name: berlingame
    tasks_from: import_sql
  when: lookup('env','run_import')
  tags: berlingame_import_sql
