---
- name: Make sure we have a group
  group:
    name: "{{ node_webpage_group }}"
    state: present

- name: Create a user
  user:
    name: "{{ node_webpage_user }}"
    state: present
    groups: "{{ node_webpage_group }}"
    append: true
    create_home: true
    shell: /bin/bash

- name: Creates web directory
  file:
    path: "{{ node_webpage_path }}"
    state: directory
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"

- name: Creates data directory
  file:
    path: "{{ node_webpage_root }}/data"
    state: directory
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"

- name: Creates log directory
  file:
    path: "{{ node_webpage_log_path }}"
    state: directory
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"

- name: Systemd service
  template:
    src: node-webpage.service.j2
    dest: /etc/systemd/system/{{ node_webpage_service_name }}.service
    owner: root
    group: root
    mode: 0644
  notify: restart {{ node_webpage_service_name }}

- name: Create .env file
  template:
    src: "env-{{ node_webpage_service_name }}.j2"
    dest: "{{ node_webpage_root }}/.env"
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"
    mode: 0644

- name: Temp .js file
  template:
    src: helloworld.js.j2
    dest: "{{ node_webpage_path }}/helloworld.js"
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"
    mode: 0644

- name: Check that the package.json exists
  stat:
    path: "{{ node_webpage_path }}/package.json"
  register: package_json_result

- name: Temp package.json file
  template:
    src: package.json
    dest: "{{ node_webpage_path }}/package.json"
    owner: "{{ node_webpage_user }}"
    group: "{{ node_webpage_group }}"
    mode: 0644
  when: package_json_result.stat.exists == False

- name: Start service
  systemd:
    name: "{{ node_webpage_service_name }}"
    state: started
    enabled: true

- name: Setup cron job for backup
  cron:
    name: "{{ node_webpage_service_name }} backup"
    minute: "33"
    user: root
    job: "{{ node_webpage_backup_script_path }}"

- name: Backup to dropbox script
  template:
    src: backup.sh.j2
    dest: "{{ node_webpage_backup_script_path }}"
    owner: root
    group: root
    mode: 0755

- name: Setup logrotate for {{ node_webpage_service_name }}
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{ node_webpage_service_name }}
    owner: root
    group: root
    mode: 0644
