---
- name: Creates directory
  file:
    path: "{{ graphs_path }}"
    state: directory

- git:
    repo: "{{ github_repo }}"
    dest: "{{ graphs_path }}"
    force: true

- name: Create .env file
  template:
    src: env.j2
    dest: "{{ graphs_path }}/.env"
    owner: root
    group: root
    mode: 0644

- name: Install packages based on package.json.
  npm:
    path: "{{ graphs_path }}"

- name: Install bower dependencies
  shell: |
    cd {{ graphs_path }} && npx bower install --allow-root

- name: Systemd service
  template:
    src: graphs.service.j2
    dest: /etc/systemd/system/graphs.service
    owner: root
    group: root
    mode: 0644
  notify: restart graphs

- name: Start service
  systemd:
    name: graphs
    state: started
    enabled: true
