---
- name: Install packages required by puppeteer (headless chrome)
  apt: name={{ chrome_headless_dependencies }} state=latest

- import_role:
    name: node-webpage
    vars_from: "reality-scrapper"
