---
email_address: "martinbartusek@gmail.com"
graphs_service_port: 3000
blog_path: /srv/blog/
berlingame_service_port: 2000
net_worth_service_port: 4000
plausible_port: 5000
spolek_path: /srv/spolek/
